In [1]:
import numpy as np

In [2]:
arr=np.array(np.random.randint(0,100,(4,5)))

In [3]:
arr

array([[ 6, 63, 33, 23, 98],
       [69, 36, 26, 24, 92],
       [56, 74, 38, 77, 26],
       [74, 20, 29, 29,  4]])

In [4]:
arr.mean(axis=1)

array([44.6, 49.4, 54.2, 31.2])

In [5]:
arr.std(axis=1)

array([32.49984615, 26.72526894, 19.86353443, 23.26714422])

In [6]:
arr.var(axis=1)

array([1056.24,  714.24,  394.56,  541.36])

In [9]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
b=np.array(B)

In [10]:
b.argsort()

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5])

In [13]:
m=int(input("Enter m"))
n=int(input("Enter n"))
c=np.array(np.random.randint(0,100,(m,n)))
c

array([[14,  1, 30, 60, 16],
       [93, 49, 41, 52,  1],
       [96, 66, 20, 56, 75],
       [ 1, 96, 99, 39, 25]])

In [14]:
c.shape

(4, 5)

In [15]:
type(c)

numpy.ndarray

In [16]:
c.dtype

dtype('int64')

In [17]:
c.reshape(n,m)

array([[14,  1, 30, 60],
       [16, 93, 49, 41],
       [52,  1, 96, 66],
       [20, 56, 75,  1],
       [96, 99, 39, 25]])